customhost = "employeee.clmnyzwtgpvv.ap-south-1.rds.amazonaws.com"
customuser = "ShaikFyrozBhanu"
custompass = "ShaikFyrozBhanu"
customdb = "employeee"
custombucket = "employeeeedetails"
customregion = "ap-south-1"
